package com.carbontrack.carbontrack.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${spring.mail.username}")
    private String fromEmail;

    public void sendOtpEmail(String to, String otpCode) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(to);
            helper.setSubject("Your CarbonTrack Verification Code");

            // Modern, clean HTML template for the OTP email
            String htmlContent = """
                    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaeb; border-radius: 8px;">
                        <h2 style="color: #1a1a1a; text-align: center;">CarbonTrack Security</h2>
                        <p style="color: #4a4a4a; font-size: 16px;">Hello,</p>
                        <p style="color: #4a4a4a; font-size: 16px;">You requested a one-time password (OTP) to authenticate with CarbonTrack.</p>
                        <div style="background-color: #f4f4f5; padding: 20px; text-align: center; border-radius: 6px; margin: 20px 0;">
                            <span style="font-size: 32px; font-weight: bold; letter-spacing: 4px; color: #000000;">%s</span>
                        </div>
                        <p style="color: #4a4a4a; font-size: 14px;">This code will expire in 5 minutes. If you did not request this, please ignore this email.</p>
                        <hr style="border: none; border-top: 1px solid #eaeaeb; margin: 20px 0;" />
                        <p style="color: #8c8c8c; font-size: 12px; text-align: center;">Securely generated by CarbonTrack Architecture</p>
                    </div>
                    """.formatted(otpCode);

            helper.setText(htmlContent, true);
            mailSender.send(message);
            log.info("Successfully dispatched OTP email to {}", to);

        } catch (MessagingException e) {
            log.error("Failed to send OTP email to {}", to, e);
            throw new RuntimeException("Failed to send email. Please try again.");
        }
    }

    public void sendInviteEmail(String to, String inviteLink, String orgName) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(to);
            helper.setSubject("You've been invited to join " + orgName + " on CarbonTrack");

            String htmlContent = """
                    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaeb; border-radius: 8px;">
                        <h2 style="color: #10B981; text-align: center;">Join %s on CarbonTrack</h2>
                        <p style="color: #4a4a4a; font-size: 16px;">Hello,</p>
                        <p style="color: #4a4a4a; font-size: 16px;">You have been invited to join <strong>%s</strong>'s workspace on CarbonTrack to track and reduce corporate carbon emissions.</p>
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="%s" style="background-color: #10B981; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 16px;">Accept Invitation</a>
                        </div>
                        <p style="color: #4a4a4a; font-size: 14px;">This link will expire in 7 days. If you did not expect this invitation, please ignore this email.</p>
                        <hr style="border: none; border-top: 1px solid #eaeaeb; margin: 20px 0;" />
                        <p style="color: #8c8c8c; font-size: 12px; text-align: center;">CarbonTrack Sustainability Platform</p>
                    </div>
                    """.formatted(orgName, orgName, inviteLink);

            helper.setText(htmlContent, true);
            mailSender.send(message);
            log.info("Successfully dispatched invite email to {}", to);

        } catch (MessagingException e) {
            log.error("Failed to send invite email to {}", to, e);
            throw new RuntimeException("Failed to send email. Please try again.");
        }
    }
}
